on:
  push:
    tags:
      - '*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to the Container registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Debian Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        context: debian/.
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/ducksify/molecule/debian:latest

    - name: Build and push Ubuntu Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        context: ubuntu/.
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/ducksify/molecule/ubuntu:latest
        
    - name: Build and push Centos7 Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        context: centos7/.
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/ducksify/molecule/centos7:latest
        
    - name: Build and push Centos8 Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        context: centos8/.
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/ducksify/molecule/centos8:latest
